[build]
  command = "sed -i \"s|__GOOGLE_API_KEY__|${GOOGLE_API_KEY}|g\" index.html"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
